import { useRef } from "react";
import html2canvas from "html2canvas";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { DrinkResult } from "@/lib/drinkGenerator";
import { useToast } from "@/hooks/use-toast";
import { 
  Thermometer, 
  Droplets, 
  Flame, 
  Sparkles, 
  RotateCcw,
  Share2,
  Download,
  Check
} from "lucide-react";

interface ResultCardProps {
  result: DrinkResult;
  onBlendAgain: () => void;
}

export default function ResultCard({ result, onBlendAgain }: ResultCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  const generateSummaryPNG = () => {
    const canvas = document.createElement("canvas");
    canvas.width = 1200;
    canvas.height = 1600;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    ctx.fillStyle = "#f3f0e9";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    let yPos = 100;

    ctx.font = "bold 60px Montserrat";
    ctx.fillStyle = "#00704A";
    ctx.textAlign = "center";
    ctx.fillText("My Personality Drink", canvas.width / 2, yPos);

    yPos += 100;
    ctx.font = "40px Open Sans";
    ctx.fillStyle = "#1E3932";
    ctx.fillText(result.drinkName, canvas.width / 2, yPos);

    yPos += 80;
    ctx.font = "24px Open Sans";
    ctx.fillStyle = "#505050";
    ctx.textAlign = "left";
    const descLines = result.description.match(/.{1,60}/g) || [];
    descLines.forEach((line) => {
      ctx.fillText(line, 60, yPos);
      yPos += 40;
    });

    yPos += 40;
    ctx.font = "bold 36px Montserrat";
    ctx.fillStyle = "#00704A";
    ctx.fillText("Flavor Profile", 60, yPos);

    yPos += 60;
    ctx.font = "28px Open Sans";
    ctx.fillStyle = "#1E3932";
    const profileInfo = [
      `Temperature: ${result.flavorProfile.temperature}`,
      `Sweetness: ${result.flavorProfile.sweetness}`,
      `Intensity: ${result.flavorProfile.intensity}`,
    ];
    profileInfo.forEach((info) => {
      ctx.fillText(info, 80, yPos);
      yPos += 50;
    });

    yPos += 20;
    ctx.font = "bold 32px Montserrat";
    ctx.fillStyle = "#00704A";
    ctx.fillText("Notes:", 80, yPos);

    yPos += 50;
    ctx.font = "24px Open Sans";
    ctx.fillStyle = "#1E3932";
    result.flavorProfile.notes.forEach((note) => {
      ctx.fillText(`• ${note}`, 100, yPos);
      yPos += 40;
    });

    yPos += 40;
    ctx.font = "bold 36px Montserrat";
    ctx.fillStyle = "#00704A";
    ctx.fillText("Why This Drink?", 60, yPos);

    yPos += 60;
    ctx.font = "22px Open Sans";
    ctx.fillStyle = "#505050";
    const whyLines = result.whyMatch.match(/.{1,70}/g) || [];
    whyLines.forEach((line) => {
      ctx.fillText(line, 60, yPos);
      yPos += 35;
    });

    yPos += 40;
    ctx.font = "italic 20px Open Sans";
    ctx.fillStyle = "#808080";
    ctx.textAlign = "center";
    ctx.fillText("Generated by Personality Blender", canvas.width / 2, canvas.height - 40);

    canvas.toBlob((blob) => {
      if (!blob) return;
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `${result.drinkName.replace(/\s+/g, "-").toLowerCase()}-personality-drink-summary.png`;
      link.style.display = "none";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    });
  };

  const handleDownloadCard = async () => {
    if (!cardRef.current) return;
    
    try {
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: "#f3f0e9",
        scale: 2,
        logging: false,
        useCORS: true,
        allowTaint: true,
        removeContainer: true,
        width: cardRef.current.offsetWidth,
        height: cardRef.current.offsetHeight,
      });
      
      const link = document.createElement("a");
      link.href = canvas.toDataURL("image/png");
      link.download = `${result.drinkName.replace(/\s+/g, "-").toLowerCase()}-personality-drink.png`;
      link.style.display = "none";
      document.body.appendChild(link);
      link.click();
      setTimeout(() => {
        document.body.removeChild(link);
      }, 100);

      generateSummaryPNG();

      toast({
        title: `${result.drinkName} - Downloaded!`,
        description: `Card image & summary PNG downloaded. Temperature: ${result.flavorProfile.temperature} • Sweetness: ${result.flavorProfile.sweetness} • Intensity: ${result.flavorProfile.intensity}`,
        duration: 5000,
      });
    } catch (error) {
      console.error("Failed to download card:", error);
      toast({
        title: "Download Failed",
        description: "Failed to download card. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `My Personality Drink: ${result.drinkName}`,
        text: `I just discovered my personality drink - ${result.drinkName}! ${result.description}`,
        url: window.location.href,
      }).catch(() => {});
    } else {
      navigator.clipboard.writeText(
        `My Personality Drink: ${result.drinkName} - ${result.description}`
      );
      console.log("Copied to clipboard!");
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto animate-fade-in">
      <div ref={cardRef} className="bg-background rounded-lg border border-border shadow-lg p-8 md:p-10">
        <div className="flex flex-col items-center text-center gap-6">
          <div 
            className="relative w-48 h-48 md:w-56 md:h-56 rounded-2xl overflow-hidden shadow-xl"
            style={{ 
              boxShadow: `0 0 0 4px ${result.gradientColors[1]}40, 0 25px 50px -12px rgba(0, 0, 0, 0.25)`
            }}
          >
            <img
              src={result.image}
              alt={result.drinkName}
              className="w-full h-full object-cover"
              data-testid="img-drink"
            />
          </div>

          <div>
            <h2 
              className="text-2xl md:text-3xl font-bold font-['Montserrat'] text-foreground mb-3"
              data-testid="text-drink-name"
            >
              {result.drinkName}
            </h2>
            <p className="text-base md:text-lg text-muted-foreground font-['Open_Sans'] leading-relaxed">
              {result.description}
            </p>
          </div>

          <div className="w-full grid grid-cols-2 gap-4">
            <div className="flex items-center gap-3 p-4 rounded-lg bg-muted/50">
              <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                <Thermometer className="w-5 h-5 text-primary" />
              </div>
              <div className="text-left">
                <p className="text-xs text-muted-foreground font-['Montserrat'] uppercase tracking-wide">Temperature</p>
                <p className="font-semibold font-['Montserrat'] text-foreground">{result.flavorProfile.temperature}</p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 rounded-lg bg-muted/50">
              <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                <Droplets className="w-5 h-5 text-primary" />
              </div>
              <div className="text-left">
                <p className="text-xs text-muted-foreground font-['Montserrat'] uppercase tracking-wide">Sweetness</p>
                <p className="font-semibold font-['Montserrat'] text-foreground">{result.flavorProfile.sweetness}</p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 rounded-lg bg-muted/50">
              <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                <Flame className="w-5 h-5 text-primary" />
              </div>
              <div className="text-left">
                <p className="text-xs text-muted-foreground font-['Montserrat'] uppercase tracking-wide">Intensity</p>
                <p className="font-semibold font-['Montserrat'] text-foreground">{result.flavorProfile.intensity}</p>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 rounded-lg bg-muted/50">
              <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-primary" />
              </div>
              <div className="text-left">
                <p className="text-xs text-muted-foreground font-['Montserrat'] uppercase tracking-wide">Notes</p>
                <p className="font-semibold font-['Montserrat'] text-foreground text-sm">
                  {result.flavorProfile.notes.slice(0, 2).join(", ")}
                </p>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 justify-center">
            {result.flavorProfile.notes.map((note, index) => (
              <Badge 
                key={index} 
                variant="secondary"
                className="font-['Montserrat']"
              >
                {note}
              </Badge>
            ))}
          </div>

          <div className="w-full p-6 rounded-lg bg-muted/30 border border-border">
            <h3 className="text-lg font-semibold font-['Montserrat'] text-foreground mb-3 flex items-center gap-2 justify-center">
              <Sparkles className="w-5 h-5 text-chart-2" />
              Why This Drink?
            </h3>
            <p className="text-muted-foreground font-['Open_Sans'] leading-relaxed">
              {result.whyMatch}
            </p>
          </div>

          <div className="flex flex-col gap-3 w-full">
            <div className="flex flex-col sm:flex-row gap-3 w-full">
              <Button
                onClick={onBlendAgain}
                className="flex-1 font-['Montserrat'] font-semibold"
                data-testid="button-blend-again"
              >
                <RotateCcw className="w-4 h-4 mr-2" />
                Blend Again
              </Button>
              <Button
                variant="outline"
                onClick={handleShare}
                className="flex-1 font-['Montserrat'] font-semibold"
                data-testid="button-share"
              >
                <Share2 className="w-4 h-4 mr-2" />
                Share Result
              </Button>
            </div>
            <Button
              variant="secondary"
              onClick={handleDownloadCard}
              className="w-full font-['Montserrat'] font-semibold"
              data-testid="button-download-card"
            >
              <Download className="w-4 h-4 mr-2" />
              Download Card
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
